# Site settings
title: AED Sim
description: An automated external defibrillator (AED) simulator for iPhone and iPad. No ads. Privacy respected.
url: https://aedsim.com
icon: /icon.png
start_year: 2010
author:
  name: Gerry Shaw
  email: gerry_shaw@yahoo.com
  url: https://gshaw.ca

# Build settings
markdown: kramdown

kramdown:
  input: GFM

exclude: [
  "AGENTS.md",
  "CLAUDE.md",
  "cspell.config.yaml",
  "Gemfile",
  "Gemfile.lock",
  "LICENSE",
  "README.md",
  "vendor"
]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
